version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  postgresTest:
    image: postgres:15
    container_name: postgres_db_test
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "5435:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - backend


  nest-app:
    build: .
    container_name: nest_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - postgresTest
    env_file:
      - .env.docker
    networks:
      - backend
    


volumes:
  postgres_data:
  postgres_data_test:

networks:
  backend:
    driver: bridge
